birdColors = {
    "Prothonotary Warbler": ["green4", "gold"],
    "Virginia Rail": ["seashell4", "saddle brown"],
    "Sora": ["seashell3", "brown4"],
    "Tundra Swan": ["gold", "white smoke"],
    "Red Crossbill": ["burlywood1", "red3"],
    "Common Redpoll": ["sandy brown", "red"],
    "White-winged Crossbill": ["white", "red3"],
    "Vesper Sparrow": ["khaki", "khaki"],
    "Red-throated Loon": ["red2", "black"],
    "Rough-legged Hawk": ["brown4", "DarkOrange4"],
    "Evening Grosbeak": ["black", "yellow"],
    "Golden Eagle": ["brown4", "brown4"],
    "Slaty-backed Gull": ["gray32", "white smoke"],
    "Pine Siskin": ["khaki", "yellow"],
    "Savannah Sparrow": ["yellow2", "khaki"],
    "Yellow-billed Cuckoo": ["brown4", "yellow"],
    "Alder Flycatcher": ["dark green", "khaki"],
    "Whimbrel": ["NavajoWhite3", "NavajoWhite3"],
    "Gray-cheeked Thrush": ["khaki4", "gray50"],
    "Brant": ["black", "brown4"],
    "Rusty Blackbird": ["gray21", "gray21"],
    "Yellow-headed Blackbird": ["yellow", "black"],
    "Wood Thrush": ["OrangeRed4", "khaki"],
    "Ruddy Duck": ["SteelBlue1", "OrangeRed4"],
    "Carolina Wren": ["khaki", "brown4"],
    "American Tree Sparrow": ["wheat4", "khaki"],
    "Eastern Bluebird": ["orange red", "dodger blue"],
    "American Pipit": ["wheat4", "khaki"],
    "Marsh Wren": ["khaki", "brown4"],
    "Field Sparrow": ["dark khaki", "dark khaki"],
    "Lincoln's Sparrow": ["gold2", "gold3"],
    "Swainson's Thrush": ["brown4", "khaki"],
    "Solitary Sandpiper": ["dark khaki", "khaki"],
    "Mourning Warbler": ["yellow", "gray40"],
    "Blue-winged Teal": ["khaki", "SteekBlue1"],
    "Semipalmated Plover": ["khaki", "khaki"],
    "Baird's Sandpiper": ["khaki", "khaki"],
    "Least Sandpiper": ["khaki", "khaki"],
    "Pectoral Sandpiper": ["khaki", "khaki"],
    "Greater Yellowlegs": ["yellow", "khaki"],
    "Lesser Yellowlegs": ["yellow", "khaki"],
    "Northern Harrier": ["gray65", "gray65"],
    "Wilson's Warbler": ["black", "gold"],
    "Northern Waterthrush": ["khaki", "dark khaki"],
    "Olive-sided Flycatcher": ["dark green", "dark olive green"],
    "Spotted Sandpiper": ["burlywood4", "burlywood1"],
    "Peregrine Falcon": ["brown4", "light goldenrod"],
    "Cliff Swallow": ["khaki", "medium blue"],
    "Black-billed Cuckoo": ["brown4", "black"],
    "Indigo Bunting": ["black", "RoyalBlue1"],
    "Merlin": ["brown4", "burlywood3"],
    "Red-headed Woodpecker": ["black", "red"],
    "Willow Flycatcher": ["olive drab", "khaki"],
    "Great Crested Flycatcher": ["olive drab", "light goldenrod"],
    "Scarlet Tanager": ["black", "red2"],
    "Canvasback": ["white", "red4"],
    "Killdeer": ["brown4", "white smoke"],
    "Semipalmated Sandpiper": ["khaki", "khaki"],
    "Caspian Tern": ["white", "orange red"],
    "Yellow-bellied Flycatcher": ["olive drab", "gold"],
    "Canada Warbler": ["gray45", "gold"],
    "Orchard Oriole": ["black", "OrangeRed3"],
    "House Wren": ["khaki", "brown4"],
    "Philadelphia Vireo": ["dark khaki", "gray70"],
    "Red-eyed Vireo": ["olive drab", "red3"],
    "Tennessee Warbler": ["olive drab", "gray36"],
    "Eastern Wood-Pewee": ["dark green", "yellow green"],
    "Brown Thrasher": ["DarkOrange4", "DarkOrange4"],
    "American Redstart": ["black", "red2"],
    "Cape May Warbler": ["yellow", "olive drab"],
    "Bay-breasted Warbler": ["khaki2", "firebrick4"],
    "Blackpoll Warbler": ["white", "black"],
    "Purple Martin": ["black", "purple4"],
    "Northern Parula": ["gray55", "gold"],
    "Magnolia Warbler": ["gray45", "gold"],
    "Ruby-throated Hummingbird": ["dark green", "maroon"],
    "Common Tern": ["black", "snow"],
    "Gray Catbird": ["black", "gray36"],
    "Bobolink": ["goldenrod", "black"],
    "Common Yellowthroat": ["yellow", "black"],
    "Least Flycatcher": ["khaki", "olive drab"],
    "Yellow-throated Vireo": ["gray60", "yellow green"],
    "White-crowned Sparrow": ["brown4", "white"],
    "Ovenbird": ["khaki", "khaki3"],
    "Blackburnian Warbler": ["black", "orange red"],
    "Black-throated Blue Warbler": ["white", "midnight blue"],
    "Rose-breasted Grosbeak": ["black", "pale violet red"],
    "Wild Turkey": ["brown4", "brown4"],
    "Black-backed Woodpecker": ["yellow", "black"],
    "Ring-necked Duck": ["white", "black"],
    "Broad-winged Hawk": ["burlywood4", "brown4"],
    "Common Raven": ["gray20", "black"],
    "Chimney Swift": ["sienna4", "saddle brown"],
    "Blue-headed Vireo": ["olive drab", "slate blue"],
    "Warbling Vireo": ["light goldenrod", "gray63"],
    "Barn Swallow": ["light goldenrod", "medium blue"],
    "Yellow Warbler": ["dark goldenrod", "yellow"],
    "Eastern Screech-Owl": ["gray60", "gray40"],
    "Eastern Kingbird": ["NavajoWhite3", "black"],
    "Veery": ["khaki", "khaki2"],
    "Baltimore Oriole": ["black", "orange"],
    "Black-and-white Warbler": ["black", "white"],
    "Chestnut-sided Warbler": ["gold", "saddle brown"],
    "Palm Warbler": ["red3", "sandy brown"],
    "Black-throated Green Warbler": ["black", "green yellow"],
    "Green Heron": ["blue3", "dark green"],
    "Common Gallinule": ["red", "black"],
    "American Coot": ["white", "black"],
    "Snowy Egret": ["white", "white"],
    "Sandhill Crane": ["dark khaki", "red3"],
    "Bonaparte's Gull": ["black", "white"],
    "Osprey": ["black", "white"],
    "Common Nighthawk": ["brown4", "brown4"],
    "Northern Rough-winged Swallow": ["khaki", "brown3"],
    "Bank Swallow": ["khaki", "medium blue"],
    "White-throated Sparrow": ["white", "brown4"],
    "Nashville Warbler": ["yellow green", "gray70"],
    "Blue-gray Gnatcatcher": ["black", "steel blue"],
    "American Goldfinch": ["black", "yellow"],
    "Chipping Sparrow": ["burlywood4", "DarkOrange2"],
    "Hermit Thrush": ["khaki4", "khaki2"],
    "Pine Warbler": ["gold", "OliveDrab1"],
    "Black Vulture": ["black", "gray70"],
    "Swamp Sparrow": ["brown4", "gray38"],
    "Pied-billed Grebe": ["gray42", "LightSteelBlue2"],
    "Yellow-bellied Sapsucker": ["black", "light goldenrod"],
    "Winter Wren": ["khaki", "saddle brown"],
    "Ruby-crowned Kinglet": ["olive drab", "red4"],
    "Purple Finch": ["burlywood4", "IndianRed4"],
    "Cackling Goose": ["snow", "brown4"],
    "Pileated Woodpecker": ["black", "red"],
    "Fox Sparrow": ["brown4", "red4"],
    "Yellow-rumped Warbler": ["gray54", "gold"],
    "Brown-headed Cowbird": ["black", "brown4"],
    "Green-winged Teal": ["black", "medium sea green"],
    "Red-necked Grebe": ["snow4", "orange red"],
    "Northern Saw-whet Owl": ["khaki", "brown3"],
    "American Kestrel": ["gray57", "orange2"],
    "Gadwall": ["khaki", "saddle brown"],
    "Golden-crowned Kinglet": ["olive drab", "gold"],
    "Common Grackle": ["black", "dark violet"],
    "Great Horned Owl": ["black", "brown4"],
    "Sharp-shinned Hawk": ["gray40", "orange"],
    "Glaucous Gull": ["old lace", "snow"],
    "American Crow": ["black", "black"],
    "White-winged Scoter": ["black", "white"],
    "Cooper's Hawk": ["gray40", "dark orange"],
    "Snowy Owl": ["white smoke", "snow"],
    "Song Sparrow": ["khaki", "sandy brown"],
    "Wood Duck": ["saddle brown", "DodgerBlue3"],
    "Red-breasted Nuthatch": ["gray35", "OrangeRed3"],
    "Brown Creeper": ["brown4", "saddle brown"],
    "American Black Duck": ["black", "brown4"],
    "Iceland Gull": ["snow", "snow"],
    "Northern Mockingbird": ["white", "gray56"],
    "House Finch": ["brown4", "firebrick3"],
    "Boreal Chickadee": ["brown4", "black"],
    "White-breasted Nuthatch": ["white", "gray35"],
    "Tufted Titmouse": ["white", "gray70"],
    "Cedar Waxwing": ["yellow", "khaki3"],
    "Trumpeter Swan": ["black", "snow"],
    "Redhead": ["black", "red4"],
    "Greater Scaup": ["white", "gray10"],
    "Lesser Scaup": ["white", "black"],
    "Long-tailed Duck": ["snow", "dark slate gray"],
    "Bufflehead": ["snow", "black"],
    "Common Goldeneye": ["snow", "black"],
    "Hooded Merganser": ["brown4", "brown4"],
    "Red-breasted Merganser": ["brown4", "saddle brown"],
    "Mourning Dove": ["dark khaki", "tan2"],
    "Red-bellied Woodpecker": ["black", "red"],
    "Northern Shoveler": ["white", "dark green"],
    "Red-tailed Hawk": ["OrangeRed3", "chocolate3"],
    "Dark-eyed Junco": ["white", "gray42"],
    "Orange-crowned Warbler": ["orange", "olive drab"],
    "Common Loon": ["white", "black"],
    "Turkey Vulture": ["tomato", "brown4"],
    "Hairy Woodpecker": ["snow", "black"],
    "Double-crested Cormorant": ["black", "black"],
    "Great Egret": ["black", "white"],
    "Black-crowned Night-Heron": ["gray50", "light yellow"],
    "Belted Kingfisher": ["white", "dark slate blue"],
    "Blue Jay": ["white", "RoyalBlue1"],
    "Northern Flicker": ["yellow", "tan4"],
    "Ring-billed Gull": ["gray68", "white"],
    "Great Blue Heron": ["white", "DeepSkyBlue4"],
    "Common Merganser": ["white", "burlywood4"],
    "Lesser Black-backed Gull": ["gray30", "linen"],
    "Great Black-backed Gull": ["gray20", "snow"],
    "Mute Swan": ["orange", "white"],
    "Rock Pigeon (Feral Pigeon)": ["gray25", "gray44"],
    "Herring Gull": ["snow", "gray56"],
    "European Starling": ["dark violet", "black"],
    "Canada Goose": ["white", "tan4"],
    "Mallard": ["saddle brown", "forest green"],
    "Downy Woodpecker": ["white", "black"],
    "Eastern Phoebe": ["brown4", "khaki"],
    "Black-capped Chickadee": ["black", "khaki4"],
    "Tree Swallow": ["old lace", "medium blue"],
    "American Robin": ["black", "orange red"],
    "House Sparrow": ["khaki3", "tan4"],
    "Eastern Towhee": ["red3", "saddle brown"],
    "Red-winged Blackbird": ["red", "black"],
    "Northern Cardinal": ["red2", "red2"],
    "Bald Eagle": ["snow", "brown4"],
    "Red-shouldered Hawk": ["OrangeRed2", "DarkOrange3"],
    "Fish Crow": ["gray19", "black"]
}

family_colors = {
  "Waterfowl": {"beige"},
  "Grouse, Quail, and Allies": {"orange"},
  "Grebes": {"gray"},
  "Pigeons and Doves": {"gray"},
  "Cuckoos": {"lightgreen"},
  "Nightjars": {"black"},
  "Swifts": {"beige"},
  "Hummingbirds": {"lightgreen"},
  "Rails, Gallinules, and Allies": {"gray"},
  "Cranes": {"orange"},
  "Shorebirds": {"lightred"},
  "Skuas and Jaegers": {"white"},
  "Alcids": {"white"},
  "Gulls, Terns, and Skimmers": {"white"},
  "Loons": {"black"},
  "Albatrosses": {"white"},
  "Petrels, Shearwaters, and Diving-Petrels": {"white"},
  "Storks": {"white"},
  "Frigatebirds, Boobies, and Gannets": {"white"},
  "Cormorants and Anhingas": {"black"},
  "Pelicans": {"white"},
  "Herons, Ibis, and Allies": {"lightblue"},
  "Vultures, Hawks, and Allies": {"darkred"},
  "Owls": {"darkred"},
  "Kingfishers": {"darkblue"},
  "Woodpeckers": {"lightgray"},
  "Falcons and Caracaras": {"black"},
  "Cockatoos": {"white"},
  "Parrots, Parakeets, and Allies": {"yellow"},
  "Tyrant Flycatchers: Pewees, Kingbirds, and Allies": {"darkgreen"},
  "Vireos": {"lightgreen"},
  "Shrikes": {"lightgray"},
  "Jays, Magpies, Crows, and Ravens": {"black"},
  "Tits, Chickadees, and Titmice": {"beige"},
  "Larks": {"beige"},
  "Martins and Swallows": {"purple"},
  "Kinglets": {"lightgreen"},
  "Nuthatches": {"orange"},
  "Treecreepers": {"darkred"},
  "Gnatcatchers": {"blue"},
  "Wrens": {"orange"},
  "Starlings and Mynas": {"darkpurple"},
  "Catbirds, Mockingbirds, and Thrashers": {"gray"},
  "Thrushes": {"darkred"},
  "Old World Sparrows": {"beige"},
  "Waxwings": {"orange"},
  "Silky-flycatchers": {"green"},
  "Wagtails and Pipits": {"white"},
  "Finches, Euphonias, and Allies": {"darkgreen"},
  "Longspurs and Snow Buntings": {"darkgreen"},
  "New World Sparrows": {"beige"},
  "Yellow-breastedChat": {"lightgreen"},
  "Blackbirds": {"black"},
  "Wood-Warblers": {"lightgreen"},
  "Cardinals, Grosbeaks, and Allies": {"red"},
  "Others": {"white"}
}